#pragma once

#include <NNClient/registry/commands/back/assignsm.h>
#include <NNClient/registry/commands/back/checkfreegpumemory.h>
#include <NNClient/registry/commands/back/crushnow.h>
#include <NNClient/registry/commands/back/detectmmr.h>
#include <NNClient/registry/commands/back/detectmmrasync.h>
#include <NNClient/registry/commands/back/detectbelts.h>
#include <NNClient/registry/commands/back/detecttrucks.h>
#include <NNClient/registry/commands/back/detecttrucksasync.h>
#include <NNClient/registry/commands/back/detectvehicles.h>
#include <NNClient/registry/commands/back/getalarmids.h>
#include <NNClient/registry/commands/back/getbboxes.h>
#include <NNClient/registry/commands/back/getbboxesasync.h>
#include <NNClient/registry/commands/back/getchars.h>
#include <NNClient/registry/commands/back/getclassification.h>
#include <NNClient/registry/commands/back/getcudadevices.h>
#include <NNClient/registry/commands/back/gethelmetbboxes.h>
#include <NNClient/registry/commands/back/gethumankeypoints.h>
#include <NNClient/registry/commands/back/gethumankeypointsasync.h>
#include <NNClient/registry/commands/back/getopenvinodevices.h>
#include <NNClient/registry/commands/back/getsemseg.h>
#include <NNClient/registry/commands/back/gettracksandkeypoints.h>
#include <NNClient/registry/commands/back/isready.h>
#include <NNClient/registry/commands/back/resizeinput.h>
#include <NNClient/registry/commands/back/setagemax.h>
#include <NNClient/registry/commands/back/setclassifiercaffe2.h>
#include <NNClient/registry/commands/back/setdetectorbytextbufferscaffe2.h>
#include <NNClient/registry/commands/back/setdetectorbytextbufferscaffe2async.h>
#include <NNClient/registry/commands/back/setdetectorbytextbuffersopenvino.h>
#include <NNClient/registry/commands/back/setfwtiemout.h>
#include <NNClient/registry/commands/back/setlabels.h>
#include <NNClient/registry/commands/back/setmaxtimesincematch.h>
#include <NNClient/registry/commands/back/setnchannels.h>
#include <NNClient/registry/commands/back/setpredicttime.h>
#include <NNClient/registry/commands/back/setsizedivisibility.h>
#include <NNClient/registry/commands/back/settrackernireq.h>
#include <NNClient/registry/commands/back/setupbodytrackcaffe2.h>
#include <NNClient/registry/commands/back/setupbodytrackcaffe2async.h>
#include <NNClient/registry/commands/back/setupbodytrackopenvino.h>
#include <NNClient/registry/commands/back/setupcharclassifiercaffe2.h>
#include <NNClient/registry/commands/back/setupcharclassifieropenvino.h>
#include <NNClient/registry/commands/back/setupchardetectorcaffe2.h>
#include <NNClient/registry/commands/back/setupchardetectoropenvino.h>
#include <NNClient/registry/commands/back/setupfpdetector.h>
#include <NNClient/registry/commands/back/setuphelmetabsencedetector.h>
#include <NNClient/registry/commands/back/setupmmr.h>
#include <NNClient/registry/commands/back/setupmmrcolorclassifiercaffe2.h>
#include <NNClient/registry/commands/back/setupmmrmmclassifiercaffe2.h>
#include <NNClient/registry/commands/back/setupmmrcolorclassifieropenvino.h>
#include <NNClient/registry/commands/back/setupmmrmmclassifieropenvino.h>
#include <NNClient/registry/commands/back/setupsinglepersonhelmetdetectorcaffe2.h>
#include <NNClient/registry/commands/back/setuptracker.h>
#include <NNClient/registry/commands/back/setuptrackerdetectorcaffe2.h>
#include <NNClient/registry/commands/back/setuptrackerdetectoropenvino.h>
#include <NNClient/registry/commands/back/setuptrackerfeatureextractorcaffe2.h>
#include <NNClient/registry/commands/back/setuptrackerfeatureextractoropenvino.h>
#include <NNClient/registry/commands/back/setuptruckchecker.h>
